"""add_task_index

Revision ID: 1eb375a82f23
Revises: 0155c2145e80
Create Date: 2025-08-26 18:50:11.686671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1eb375a82f23'
down_revision: Union[str, None] = '0155c2145e80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_tasks_status_project_id', 'tasks', ['status', 'project_id'], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_tasks_status_project_id', table_name='tasks')
    # ### end Alembic commands ###
