"""add creator for task and change relationship between user and task

Revision ID: 50a6bce0e45e
Revises: 7d8f9e69e2bc
Create Date: 2025-08-28 16:15:36.375813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50a6bce0e45e'
down_revision: Union[str, None] = '7d8f9e69e2bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('creator_id', sa.UUID(), nullable=False))
    op.alter_column('tasks', 'due_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_foreign_key(None, 'tasks', 'users', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.alter_column('tasks', 'due_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.drop_column('tasks', 'creator_id')
    # ### end Alembic commands ###
