"""add priority and due_date to Task, add cascade

Revision ID: 7d8f9e69e2bc
Revises: 8cfdf01eb97c
Create Date: 2025-08-28 12:19:07.523153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d8f9e69e2bc'
down_revision: Union[str, None] = '8cfdf01eb97c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    taskpriorityenum = sa.Enum('LOW', 'MEDIUM', 'HIGH', name='taskpriorityenum')
    taskpriorityenum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='taskpriorityenum'), nullable=False))
    op.add_column('tasks', sa.Column('due_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'due_date')
    op.drop_column('tasks', 'priority')
    # ### end Alembic commands ###
    taskpriorityenum = sa.Enum('LOW', 'MEDIUM', 'HIGH', name='taskpriorityenum')
    taskpriorityenum.drop(op.get_bind(), checkfirst=True)
