"""{{update attactment author}}

Revision ID: cfd5e70dd177
Revises: 50a6bce0e45e
Create Date: 2025-08-31 15:09:49.597815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfd5e70dd177'
down_revision: Union[str, None] = '50a6bce0e45e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('author_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'attachments', 'users', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attachments', type_='foreignkey')
    op.drop_column('attachments', 'author_id')
    # ### end Alembic commands ###
